swagger: '2.0'
info:
  version: 1.0.0
  title: Revolut transfer API
host: localhost:7000
basePath: /api
tags:
  - name: account
    description: everything about accounts
  - name: transfer
    description: transfer money between accounts
schemes:
  - http
paths:
  '/accounts/{accountId}':
    get:
      tags:
        - account
      summary: Get account by ID
      description: Returns a single account
      operationId: getAccountById
      produces:
        - application/json
      parameters:
        - name: accountId
          in: path
          description: ID of account to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Account'
        '400':
          description: Invalid ID supplied
        '404':
          description: Account not found
    delete:
      tags:
        - account
      summary: Deactivate an account
      description: ''
      operationId: deactivateAccount
      produces:
        - application/json
      parameters:
        - name: accountId
          in: path
          description: ID of account to deactivate
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Account'
        '400':
          description: Invalid ID supplied
        '404':
          description: Account not found
  '/accounts/{accountId}/deposits':
     get:
      tags:
        - account
      summary: Get deposits by account ID
      description: Returns a set of deposits for account
      operationId: getDepositsByAccountId
      produces:
        - application/json
      parameters:
        - name: accountId
          in: path
          description: ID of account wich deposits need to return
          required: true
          type: integer
          format: int64
        - name: start
          in: query
          description: Deposits from this date (timestamp)
          required: false
          type: integer
          format: int64
        - name: end
          in: query
          description: Deposits to this date (timestamp)
          required: false
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/AccountOperation'
        '400':
          description: Invalid ID supplied
        '404':
          description: Account not found
  '/accounts/{accountId}/withdrawals':
     get:
      tags:
        - account
      summary: Get withdrawals by account ID
      description: Returns a set of withdrawals for account
      operationId: getWithdrawalsByAccountId
      produces:
        - application/json
      parameters:
        - name: accountId
          in: path
          description: ID of account wich withdrawals need to return
          required: true
          type: integer
          format: int64
        - name: start
          in: query
          description: Withdrawals from this date (timestamp)
          required: false
          type: integer
          format: int64
        - name: end
          in: query
          description: Withdrawals to this date (timestamp)
          required: false
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/AccountOperation'
        '400':
          description: Invalid ID supplied
        '404':
          description: Account not found
  '/accounts/customer/{customerId}':
      get:
        tags:
          - account
        summary: Find accounts by customer ID
        description: Returns an array of accounts
        operationId: findAccountsByCustomerId
        produces:
          - application/json
        parameters:
          - name: customerId
            in: path
            description: ID of accounts owner
            required: true
            type: integer
            format: int64
        responses:
          '200':
            description: successful operation
            schema:
              type: array
              items:
                $ref: '#/definitions/Account'
          '400':
            description: Invalid ID supplied
      post:
        tags:
          - account
        summary: Create an active account for a customer
        description: ''
        operationId: createAccount
        produces:
          - application/json
        parameters:
          - name: customerId
            in: path
            description: ID of account owner
            required: true
            type: integer
            format: int64
          - in: body
            name: body
            description: account to create
            required: true
            schema:
              $ref: '#/definitions/AccountToCreate'
        responses:
          '201':
            description: successful operation
            schema:
              $ref: '#/definitions/Account'
          '400':
            description: Invalid account
  '/transfers':
    post:
      tags:
        - transfer
      summary: Create a money transfer between accounts
      description: ''
      operationId: createTransfer
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: transfer to create
          required: true
          schema:
            $ref: '#/definitions/TransferToCreate'
      responses:
        '201':
          description: successful operation
          schema:
            $ref: '#/definitions/Transfer'
        '400':
          description: Invalid transfer
definitions:
  Currency:
    type: string
    description: Account currency
    enum:
      - USD
      - RUB
      - BTC
  Account:
    type: object
    properties:
      id:
        type: string
      customerId:
        type: string
      currency:
        $ref: '#/definitions/Currency'
      balance:
        type: string
      active:
        type: string
    xml:
      name: Account
  AccountToCreate:
    type: object
    properties:
      currency:
        $ref: '#/definitions/Currency'
      balance:
        type: integer
        format: int64
    xml:
      name: AccountToCreate
  AccountOperation:
      type: object
      properties:
        id:
          type: string
        executedTimestamp:
          type: string
        correspondentAccountId:
          type: string
        amount:
          type: string
      xml:
        name: AccountOperation
  Transfer:
    type: object
    properties:
      id:
        type: string
      executedTimestamp:
        type: string
      withdrawalAccountId:
        type: string
      withdrawalAccountCurrency:
        $ref: '#/definitions/Currency'
      withdrawalAmount:
        type: string
      depositAccountId:
        type: string
      depositAccountCurrency:
        $ref: '#/definitions/Currency'
      depositAmount:
        type: string
    xml:
      name: Transfer
  TransferToCreate:
    type: object
    properties:
      withdrawalAccountId:
        type: integer
        format: int64
      withdrawalAccountCurrency:
        $ref: '#/definitions/Currency'
      withdrawalAmount:
        type: number
        format: double
      depositAccountId:
        type: integer
        format: int64
      depositAccountCurrency:
        $ref: '#/definitions/Currency'
      depositAmount:
        type: number
        format: double
    xml:
      name: TransferToCreate